#define QUAD_SIZE 100
#define FLOOR_HALF_SIZE 1000
#define QUAD_NUM_LINE     (FLOOR_HALF_SIZE * 2 / QUAD_SIZE)
#define QUAD_NUM_ALL     (QUAD_NUM_LINE * QUAD_NUM_LINE)
#define VERT_NUM_LINE  (QUAD_NUM_LINE + 1)
#define VERT_NUM_ALL (VERT_NUM_LINE * VERT_NUM_LINE)